### PR TITLE
Feature/add development script to generate video files

### PR DESCRIPTION
**Pull request by pleasenophp**
usage 1 of the following:

```
npm run convert-video fr
npm run convert-video en
npm run convert-video de
npm run convert-video music
```

The last argument is Intro vide language track. Supported fr, en, de, or music-only. If no language argument is specified, the intro video will be in english.

### CODE REVIEW

**Comment by agrande** [comment]
Not sure why the linter didn't run automatically on this PR, I thought I had that in place.
Could you try running `npm run lint` locally and fix the errors before I can merge this?
Sorry for the strict linting rules, but I think it's important to keep strong conventions for code maintainability.

**Comment by agrande** [comment]
Great work, though!

**Comment by agrande** [comment]
There was something disabled in the CircleCI config, now it's gonna check linting again automatically on PRs coming from forks.

**Comment by pleasenophp** [comment]
> Not sure why the linter didn't run automatically on this PR, I thought I had that in place.
> Could you try running `npm run lint` locally and fix the errors before I can merge this?
> Sorry for the strict linting rules, but I think it's important to keep strong conventions for code maintainability.

That's fine. I will fix the lint rules when this PR is ready to merge. Now it's still a draft because intro doesn't work. Regarding console.log I guess I will suppress it as it's a dev script where console.log is needed for output.

**Comment by pleasenophp** [comment]
All tslint errors should be fixed now.

**Comment by agrande** [comment]
> That's fine. I will fix the lint rules when this PR is ready to merge. Now it's still a draft because intro doesn't work. Regarding console.log I guess I will suppress it as it's a dev script where console.log is needed for output.

Yeah, I think suppressing the console.log is fine in this case indeed.

**Pull request merged**
