### PR TITLE
Stop theme music playing when exiting VR.

### PR DESCRIPTION
**Pull request by slwilliams**
Without this we have two copies playing because we never clean up the VR state.

### CODE REVIEW

**Comment by slwilliams** [comment]
Lint failure is unrelated (existing line length issue I'm not touching).

**Comment by agrande** [comment]
Well, the lint error happens on line 301 => 306 which you did change.
Doing the bind(this) in the constructor would remove the issue, in addition to avoiding rebinding at each render() call.

**Comment by agrande** [comment]
Besides that, this PR looks good to me. Thanks!

**Comment by slwilliams** [comment]
Ah ok yea, done.

**Pull request merged**
