### PR TITLE
Script and gameplay editor improvements

### PR DESCRIPTION
**Pull request by agrande**
- Automatic compilation of scripts on changes (instead of pressing a compile button)
- Various bits for making scripts more stable when compiling incomplete commands
- Adding new points and actors

**Preview here:** https://pr-386.lba2remake.net

### CODE REVIEW

**Comment by slwilliams** [comment]
hmm preview is failing to load with:

TypeError: Cannot destructure property 'objectToAdd' of 'this.props.sharedState' as it is undefined.

**Review by xesf — APPROVED** [review]

**Comment by xesf** [comment]
Getting the same issue, but only when I am not running Editor mode. If you enable Editor mode it seems fine.

**Comment by agrande** [comment]
Oh, right, makes sense, the GameUI component doesn’t have that prop when not in editor mode. I should have tested that. Thanks for noticing!

**Comment by agrande** [comment]
I’ll fix it in a moment.

**Pull request merged**
