### PR TITLE
Release samples awhile reloading a new scene

### PR DESCRIPTION
**Pull request by xesf**
Still need to test it with VR.

@slwilliams that's the fix I mention on your previous PR.

**Preview here:** https://pr-567.lba2remake.net

### CODE REVIEW

**Comment by agrande** [comment]
Ok, I'll test this now.

**Comment by agrande** [comment]
> Ok, I'll test this now.

It didn't come as fast, but I encountered some audio issues after playing for a while. There was some stuttering at some point in a scene with many samples (not as much as before, and it got better after switching scenes, but still).
Also, all in-game audio stopped playing after some time, and I had to reload the game to get it back.

**Comment by xesf** [comment]
Needs a deeper look than. I will try tomorrow to have a look with the VR and see if I can find what's happening.
But good that there are some improvements.

**Review by agrande — APPROVED** [review]
This is an improvement already, we can always improve it more in a future PR.

**Pull request merged**
