### PR TITLE
WAIT DOOR script command

### PR DESCRIPTION
**Pull request by xesf**
**Preview here:** https://pr-558.lba2remake.net

### CODE REVIEW

**Review by slwilliams — APPROVED** [review]

**Comment by agrande** [comment]
What is this command used for?

**Comment by xesf** [comment]
> What is this command used for?

Wait door is actually what implements the opening of the doors.
when OPEN_LEFT/RIGHT/UP/DOWN is used, the script continues and checks if the door was actually open in the WAIT_DOOR. Something like the WAIT_ANIM where it waits for animation to finish, this one waits for the door to finish open.

This was causing some weird behaviour in the scripts, for example the LBA1 Outside Prison fences which has more conditions to open the fences.

**Review by agrande — APPROVED** [review]

**Comment by agrande** [comment]
Door in the temple of Bù (the ones you open when on the train) broke.
Only one of them opens.

**Comment by xesf** [comment]
> Door in the temple of Bù (the ones you open when on the train) broke.
> Only one of them opens.

Yeah, saw it now on LBA1 as well.
Looks like not all doors implement the WAIT_DOOR command.
I have a quick fix for it.

**Pull request merged**
