### PR TITLE
Include y axis during distance checks by using threejs distance function

### PR DESCRIPTION
**Pull request by xesf**
**Preview here:** https://pr-574.lba2remake.net

### CODE REVIEW

**Comment by agrande** [comment]
What prompted you to make this change?

**Comment by xesf** [comment]
> What prompted you to make this change?

On scenes where you have floors, the distance was getting calculated in 2D only for different floors.

**Comment by agrande** [comment]
Do you have examples so I can test?
This is a pretty big change as this command is used everywhere, and I seem to remember that we changed this back-and-forth in the past (but maybe I recall wrongly), so I want to test it thoroughly to make sure it doesn't break other scenes.

**Comment by xesf** [comment]
> Do you have examples so I can test?
> This is a pretty big change as this command is used everywhere, and I seem to remember that we changed this back-and-forth in the past (but maybe I recall wrongly), so I want to test it thoroughly to make sure it doesn't break other scenes.

Start LBA1 in the Prison.
Pass the first gate towards getting the holomap and id card. Stay there for awhile until the nurse in the upper floor walks.
The nurse in the upper floor will act has you are near by when you are standing below him.

I've tested a bit and seem to have not broken other commands and distance is working as expected. Other commands in the script seems to be working fine.
Perhaps we need to test more to be sure.

**Comment by agrande** [comment]
I just tested quite a bit on my own, and it seems fine.

**Review by agrande — APPROVED** [review]

**Pull request merged**
