### PR TITLE
fix size of buttons on iso layout editor for Firefox

### PR DESCRIPTION
**Pull request by felipesanches**
(issue #316)

**Preview here:** https://pr-320.lba2remake.net

### CODE REVIEW

**Comment by agrande** [comment]
Screenshot 2020-07-11 at 22 37 44
This is how it looks on chrome with your changes, 0 padding looks kind of ugly. Not sure what your browser is doing but it's adding unspecified padding there.

**Comment by agrande** [comment]
Screenshot 2020-07-11 at 22 43 10
And this is what I have on Firefox with your change.

**Comment by agrande** [comment]
In your screenshot there's clearly some padding applied, which shouldn't be the case. I think your browser is misconfigured, and not respecting the web standards. I can't accept this PR as it would deteriorate the experience for everyone else but you.

**Comment by felipesanches** [comment]
ok, let's try to figure out a better solution then...

**Comment by agrande** [comment]
What do you suggest?

**Comment by felipesanches** [comment]
I don't know... I'll have to experiment and see if someone else has already dealt with a similar discrepancy.

**Comment by agrande** [comment]
It looks weird, I've never seen that type of issue. I'm a bit at a loss here.

**Comment by agrande** [comment]
> I don't know... I'll have to experiment and see if someone else has already dealt with a similar discrepancy.

Any news on this?

**Comment by agrande** [comment]
I'm closing this as it seems to be an issue that is very specific to your own environment and the proposed fix makes things worse for everyone else. I'm leaving the related issue (#316) opened so we can keep investigating the root cause and find a better solution.

**Comment by felipesanches** [comment]
thanks!

**Pull request closed without merging**
